from __future__ import annotations

from pathlib import Path


CATEGORIES = [
    "Documents",
    "Images",
    "Videos",
    "Audio",
    "Archives",
    "Code",
    "Spreadsheets",
    "Presentations",
    "PDFs",
    "Installers",
    "Other",
]


EXTENSION_CATEGORIES = {
    ".pdf": "PDFs",
    ".doc": "Documents",
    ".docx": "Documents",
    ".odt": "Documents",
    ".pages": "Documents",
    ".txt": "Documents",
    ".rtf": "Documents",
    ".md": "Documents",
    ".jpg": "Images",
    ".jpeg": "Images",
    ".png": "Images",
    ".gif": "Images",
    ".webp": "Images",
    ".svg": "Images",
    ".bmp": "Images",
    ".tif": "Images",
    ".tiff": "Images",
    ".heic": "Images",
    ".heif": "Images",
    ".avif": "Images",
    ".ico": "Images",
    ".raw": "Images",
    ".arw": "Images",
    ".cr2": "Images",
    ".cr3": "Images",
    ".nef": "Images",
    ".nrw": "Images",
    ".orf": "Images",
    ".raf": "Images",
    ".rw2": "Images",
    ".dng": "Images",
    ".pef": "Images",
    ".srw": "Images",
    ".mp4": "Videos",
    ".mov": "Videos",
    ".avi": "Videos",
    ".mkv": "Videos",
    ".webm": "Videos",
    ".wmv": "Videos",
    ".m4v": "Videos",
    ".mp3": "Audio",
    ".wav": "Audio",
    ".flac": "Audio",
    ".aac": "Audio",
    ".m4a": "Audio",
    ".ogg": "Audio",
    ".wma": "Audio",
    ".zip": "Archives",
    ".rar": "Archives",
    ".7z": "Archives",
    ".tar": "Archives",
    ".gz": "Archives",
    ".bz2": "Archives",
    ".xz": "Archives",
    ".py": "Code",
    ".js": "Code",
    ".ts": "Code",
    ".jsx": "Code",
    ".tsx": "Code",
    ".html": "Code",
    ".htm": "Code",
    ".css": "Code",
    ".scss": "Code",
    ".json": "Code",
    ".yml": "Code",
    ".yaml": "Code",
    ".xml": "Code",
    ".toml": "Code",
    ".ini": "Code",
    ".ps1": "Code",
    ".bat": "Code",
    ".sh": "Code",
    ".java": "Code",
    ".cs": "Code",
    ".cpp": "Code",
    ".c": "Code",
    ".h": "Code",
    ".php": "Code",
    ".rb": "Code",
    ".go": "Code",
    ".rs": "Code",
    ".csv": "Spreadsheets",
    ".tsv": "Spreadsheets",
    ".xls": "Spreadsheets",
    ".xlsx": "Spreadsheets",
    ".ods": "Spreadsheets",
    ".ppt": "Presentations",
    ".pptx": "Presentations",
    ".odp": "Presentations",
    ".exe": "Installers",
    ".msi": "Installers",
    ".dmg": "Installers",
    ".pkg": "Installers",
    ".apk": "Installers",
}


def categorize_by_rules(path: Path) -> tuple[str, str]:
    category = EXTENSION_CATEGORIES.get(path.suffix.lower(), "Other")
    return category, f"Matched by extension '{path.suffix.lower() or 'none'}'."
